### ISSUE TITLE
Story Design

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#18]
Sit down for a chat to nail down the story.  Think of this as an English class short story.

Come up with answers for the following questions:

- Who are the characters (protagonist, main antagonist, supporting characters)?
- Why is the protagonist at the school?
- What is the protagonist trying to achieve?
- What is preventing the protagonist from achieving their goal?
- List the main interactions the protagonist is going to have before the climax of the narrative.
- What is the climax of the narrative?
- How does the story resolve?

**Comment by kodriq** [comment]
ok for question one
whats our protagonist's gender, age, and anything about their appearance
even if its first person i assume we would end up drawing them at some point
their clothes will prob be either uniform related, cause of school, or hospital related, cause of experiments
^it might be easier to figure out some of these details after we make the plot tho

**Comment by ediehouston** [comment]
Yeah your idea for the graphic design of the character sounds really good. I think most people are leaning towards a female character based off of the poll you made on insta. As for age and stuff do we need to go that in depth?

**Comment by ediehouston** [comment]
We should figure out why the character is at the school.

**Comment by ediehouston** [comment]
I like the idea that the character just wakes up there and that the school is prestigious and experiments on students, it could be an attempt for a more advanced society and hopes that they produce the best students. Should we do something like the character was kidnapped and brought there? Or should we keep it mysterious how the character got there, and all we know is that the character goes to the school and that they just woke up there.

**Comment by kodriq** [comment]
i think sheshould already be going to the school, cause if she is kidnapped ppl would be looking for her, but if its a boarding school she already attends nobody outside the school would realize anything was wrong

**Comment by kodriq** [comment]
and for age we could just give a range
like shes prob around 16-18 if its like a highschool boarding school

**Comment by kodriq** [comment]
ok so 
if i put (?) it means its smth that might need to be changed 

Our protagonist is a ~17 year old girl who has been enrolled in a boarding school that's in a pretty remote location(?), she attends it for two years(?), but coming up to her graduation things go wrong....
She wakes up in a dark and dingy like hospital setting, with no recollection of how she got there, all she remembers is going to sleep in her dorm(?)
She cant see anyone else, and its very creepy and dark, she finds a flashlight, an begins to explore

**Comment by kodriq** [comment]
and yeah, maybe like

1. her friend had gone missing recently, so she knew they must be down here too? 
2. She hears her friends voice, or finds smth that belongs to them?

**Comment by mya1919** [comment]
Location: maybe in like a forest area or in the mountains, something remote sounds goood
Year: maybe three years total in the school so this is final year
she we could do little flashback things of her walking to her dorm and falling alseep and then she wakes up in that different place.

**Comment by mya1919** [comment]
maybe she hears her freinds voice saying her name,
plot twist could be that the friend was never there and it was just to lure her deeper into the school but we could also do shes trying to rescue herself and her friend

**Comment by mya1919** [comment]
would have been cool if it could have been multiplayer

**Comment by kodriq** [comment]
yes
another plot twist is she might not realize at first shes in the school basement (she might think some foreign force abducted her at first)

**Comment by mya1919** [comment]
yes i like that
and then she gets to main floor after a while and realizes where she is

**Comment by kodriq** [comment]
yeah like she subconsciously starts to realize cause the layout is similar to her class but she doesnt quite realize it

**Comment by mya1919** [comment]
ok should we come up with like a step by step of the events that happen 
so they can start making the levels and stuff

**Comment by kodriq** [comment]
**level one**

Visual:
Dark, enclosed (basement) hospital setting, likely underground, creepy

Mechanics:
flashlight to see in the dark

Goal(s):

**Comment by kodriq** [comment]
^feel free to edit that and add stuff

**Comment by mya1919** [comment]
We need to figure out more of what is the goal of the antagonists is, and are there any other people around her attacking her, or is it just her. 
is this a test she is trying to pass, or is she an experiment?

one idea could be this is kind of a "final exam" to graduate, obviously, she wouldnt know that but at the end, when she finally gets out the teachers could be standing there saying "you passed" (by escaping and finding the way out)

if we do this the friend yelling out could be another "test" to pass
maybe there could be a different kind of ending if the player decides to go investigate the sound or not

**Comment by kodriq** [comment]
yes i love multiple endings
even just two (like a "good" or "bad") are awesome

**Comment by mya1919** [comment]
Like you passed you failed type thing

**Comment by kodriq** [comment]
i like ur idea, but one thing would be like 

why wouldn't people report the school for unethical testing (if they are supposed to survive and leave)
like do they sign a form first or are there memories wiped or LOL
maybe they(or their parents) get a bunch of money if they "pass"

**Comment by mya1919** [comment]
yes thats true,
maybe yes you sign something before, and with graduating this school you can kind of do anything after so its worth the risk, im not sure

**Comment by kodriq** [comment]
i guess we gotta decide if what she goes through is "all according to plan" or if she is deviating from what the "teachers" wanted

**Comment by mya1919** [comment]
yes I like that, 
like one way she passes just as shes supposed to, and the other way she escapes some other way

I feel like maybe shes not supposed to actually try and save the friend so if she does that could be the one she has to escape another way

**Comment by kodriq** [comment]
yess thats perfect

**Comment by kodriq** [comment]
we should figure out how many levels this game will have, then figure out when the two plots will deviate
we prob shouldnt seperate them too early on as it might be two hard to code two full playthroughs from the get go

(like lets say at chapter 4 u can choose 2 ways, them both stories go to chapter 6 in their own ways and have different levels)
maybe the version where u dont save the friend is also shorter too

**Comment by mya1919** [comment]
yes thats perfect

**Comment by kodriq** [comment]
i was thinking like maybe the parents are aware of all this stuff and they actually wanted this to happen because they believe it will give their kid the best start in life
(kinda like a "metaphor" for super strict parents who only care about success?)

**Comment by kodriq** [comment]
^ one way to make it so "this is how they get away with this"
then the teachers are motivated by money or they truly believe this is all beneficial idk

**Comment by Rhyswatsonn** [comment]
if we wanted to do a whole section where she has to save a friend we could make it like she is locked in a room and you have to solve puzzles/ find keys or something to get her out. ofc that doesn't need to go to plan but could ad some volume to the plot

**Comment by kodriq** [comment]
yeah for dialogue i pictured it would be something like that, where it would be a user interface and you click to go through it or its a cutscene that plays itself (either would work)

**Comment by kodriq** [comment]
we should figure out exactly who the enemies are
and what this whole "test" thing is, and also did the teachers medically experiment on them? if so what did they do to them? and what makes our protagonist different
cause idk what escaping a basement would really have to do with school smarts, so we gotta figure out why

**Comment by ediehouston** [comment]
Yeah that is true. Should the enemies be teachers and authorities from the school? I also liked the idea that was mentioned about having some spooky mutated humans that could be students who had the test done on them. I just don't know how that would go with the narrative that we have

**Comment by ediehouston** [comment]
Yeah that is a good idea. I like the idea of the plot splitting and having two alternatives of who your enemies are. I guess now we just need to figure out exactly why the teachers are testing on them, as well as how the school is getting away with it.

**Comment by kodriq** [comment]
i think the most important part is figuring out what this whole "experiment is"
so heres some brainstorm stuff

1. it cant kill the students, because people would question why there kids never came back from boarding school **UNLESS** the parents were in on it (blinded by the desire to see their kid succeed they see this mysterious school has great results for the students who make it out and are willing to take the risk?) But even then there had to be a reason the public didnt wonder why it was clear some people weren't making it out
2. Is what's happening tour protagonist going according to plan, or is she deviating from what was supposed to happen? (in the save the friend route i assume that would be deviating, but how about leading up to that?)
3. How are the teachers ok with doing this? Are they actually hurting/killing kids? Are they brainwashed?

**Comment by ediehouston** [comment]
I think having the teachers being brainwashed would be a good explanation for a lot of their actions so that might be a good thing to incorporate. As for the experiment, I think we should keep the saving the friend route so I think we should have her deviating from what was supposed to happen like you said.

**Comment by kodriq** [comment]
i dont know if this entire idea would work for the game but i think some parts might cause

1. if scientists are involved its not impossible to me that it might get unethical, history has shown a lot of unethical practices for the sake of science and if they DID intend for it to work then their intentions might not truly be evil
2. For the friend part, they probably assumed the students wouldn't want to help each other (as they are drive to survive which often makes you selfish) and have probably ben pitted against each other since the beginning since this is a very academic prestigious school (but she is not supposed to help her friend and they both get in trouble if she chooses that)

**Comment by kodriq** [comment]
last thing but Maybe they let one lucky student enter through scholarship, while all the others came from wealthy families who had to pay, and that's what separates her from the others (maybe by being sheltered all their lives many of the other students were quicker to break under the pressure of survival)

**Comment by jeffaroundtheworld** [comment]
I think that is a great back story and could definitely drive the narrative.... this gives you lots of potential for side stories, quests, and a rationale for why the protagonist is there and trying to get out....

Also creates space for the friend to rescue... evil scientists/teachers.... puzzles... and numerous settings that make sense in a horror game.

> here's a way too long idea for a backstory/plot its very rough but let me know what u think of the base idea and if there's any parts you think might work well
> 
> There was a group of scientists studying evolution, and trying to find a way to force it. Studies showed that humans seemed to be getting dumber overtime, and they were looking to prevent this with the next generation (the generation our protagonist is in) They discovered that by putting a rat(or other animal) in a life threatening situation, it would seemingly get smarter, as if evolving, for the sake of survival. The rat would keep this upgrade, and preformed much greater than other rats who hadn't experienced the same "forced evolution "in later tests . They create a perfect formula that proves effective again and again for this "forced evolution" idea (with other animals too like dogs and maybe even monkeys) They deemed this theory a success, and "decided to just go for it and do humans next" LOL
> 
> They did notice that rats who had scored lower on intelligence measures before the assessment had a possibility to "go crazy" instead of "evolve", but surely that wouldn't happen with humans as long if they got clever youthful minds **(this is where the mutated students would come in)**
> 
> So this is a prestigious boarding school that prioritizes success and "genius" over anything, and the scientists come, and suggest a collaboration. They show the test results, but are vague about exactly "what" causes this jump in intelligence. (AKA the school doesn't realize the scientists plan to put their students in life threatening situations)
> 
> (also maybe the school isn't super caring about their students and mostly focus on money + success) So the scientist partner up, and the school announces a special new curriculum, and that they will only be accepting "500" students, and then "50" of them will be selected before graduation for a special assessment (the forced evolution thing) that will "be guaranteed to make them geniuses or whatever" (the rest just graduate normally as other students did before the scientists came to this school, and were told they were deemed not fit for the assessment)
> 
> **ANYWAYS** our protagonist is a girl whos parents invested everything into sending her here, and she is very ambitious and clever and manages to be chosen to be one of the "50 who get the special assessment"
> 
> And so the game is basically her doing this assessment which is run by the scientists in the basement of the school, and is basically torture to "force you into evolving driven by the need to survive" (its secretly a controlled environment but its supposed to trick the students mind and body into "survival mode"
> 
> The other students she encounters might be other kids doing the assessment, who's mind and body couldn't handle it and they became zombie like creatures running on "pure survival instinct" which makes them very dangerous (and we could make them pretty creepy or make a reason they get super deformed too 💀💀)

**Comment by ediehouston** [comment]
Yeah your overall idea and explanation sounds perfect. I also think the idea of how she didn't get affected by the experiment as badly as the other students because she was not sheltered her whole life is great because it explains a lot as to how she is different from the others, is more resilient, and it also adds some depth to her character.

**Comment by ediehouston** [comment]
We could also say since the operations were mostly tested on animals, that could be a factor as to why there were many errors when it came to performing it on humans. This could be why there were cases where it went really badly resulting in deformities in students etc.

**Comment by kodriq** [comment]
yaa exactly

**Comment by ediehouston** [comment]
Also are we saying the parents are unaware of this procedure? Or should they know about it as well as the risks of it, but they are just so drawn into their child's success they don't care.

**Comment by kodriq** [comment]
hmm i think t could go a few ways like

1. the parents are super strict and making her do this (and dont care)
2. Maybe her parents are sick/or just not well off or smth and she's motivated to get like a successful career to help them at any cost
Or.................idk what do u think

**Comment by ediehouston** [comment]
Yeah I think both those options are good, it might explain more if we say the parents are just super strict because then it could be the case for the other 49 students as well. The main character of course could have a different unique story with her parents though.

**Comment by kodriq** [comment]
ya we can go with that cause i kind of like the idea of her not being super emotional about this/be like more driven by anger at her parents and a desire to succeed

**Comment by kodriq** [comment]
ok one slight edit to the story since I think there was a small problem, which is: why is it so dark and rundown in the area they are supposed to be testing/assessing the students? 
heres a basic idea

They starting waking all the students up down there, and begun the testing,  but it went south very fast. Almost all the students were reacting wrongly, and ended up in the frenzied survival state, where they were attacking each other and the scientists manically. Unable to control them, the scientists escaped the basement and decided to observe the video cameras instead. They were arguing over what to do, whether to kill them all, wait ir out and see if they turn back, try to save them.
(this is only over the span of like 6-12 hours)

But then the protagonist wakes up, in the messed up version of how the basements started, and she begins moving though all the (kind of ruined) tests. They noticed her on the cameras, and called off the decision to possibly gas the whole basement to kill all the monster students they created (despite the fact there were a few others who hadn't turned crazy yet)
They begun observing her, and realized the test was working correctly on her, and she seemed to (slowly) be evolving. 
They then began to debate over whether to intervene and save her, but after seeing her escape/defeat another student they (selfishly) decide to wait it out and see if she can fully complete the tests according to plan (despite the fact there are crazy dangerous students running around down there)

**Comment by kodriq** [comment]
lmk ur opinion on that cause it def needs refining but i think the idea of the tests going wrong before she had woken up make sense for why its 1. all dark and 2. spooky and ruined
But the puzzles/challenges she goes through are all according to plan, but they just weren't originally in the dark and full of frenzied students LOL
Then she encounters maybe a few other students who hadn't turned crazy yet (maybe by hiding somewhere instead of continuing the tests) 
But the scientists might notice that the tests didn't work if they used teamwork (like it wouldn't help them evolve) so they try to separate them (aka they dont want her to help her friend)

**Comment by ediehouston** [comment]
Yeah that sounds good. It could also be super rundown due to the fact that the room (or basement) that the students are being tested in maybe is supposed to be hidden and concealed (since the experiments they are doing are unethical and illegal) and this could have lead the place to look more neglected. They also would not want to bring any attention to what they are doing by doing it somewhere that is modern and eye-catching.

**Comment by kodriq** [comment]
yess and though they prob got funds from the school, maybe this batch of scientists were more shady then they let on so they dont actually have lots of money or good equipment

**Comment by kodriq** [comment]
if the scientists are watching on security cameras we could have the game open with a cutscene of a security camera watching "something" (a frenzied student) like walk by a room/destroy smth/ do smth scary
something that makes a spooky start but doesn't reveal too much

**Comment by ediehouston** [comment]
Yeah I think that would make perfect sense that they would be shady like that too because of the fact that they are choosing to participate in something so unethical already.

**Comment by ediehouston** [comment]
And yeah that cut-scene would work well.

**Comment by kodriq** [comment]
for the enemies i also thought we could make 3 kinds of frenzied students
flight, fright or freeze ones that all work differently and have different mechanics to avoid/fight them
but that might be too complicated for a project of this size, as im not sure everyone will feel like coding 3 entirely different types lmfao
but we should brainstorm how they behave 
tho we could also have either a bunch that act the same or a few that are unique, it depends on how much time we have and what the plot calls for

**Comment by kodriq** [comment]
also we can decide if they can be "cured" or not
which might only depend on how many mechanics we wanna code in and how difficult would be

**Comment by ediehouston** [comment]
Yeah those are good ideas for the enemies, and worst scenario it's too much coding for three separate types we could probably just pick one of those types to try to avoid/fight and could duplicate them to have multiple.

**Comment by kodriq** [comment]
its not super urgent since we are still just starting the game, but we should start planning the endings
like

1. we dont save the friend
-leave all the other students to die and successfully passes the test (so maybe she does smart evolve) and maybe she later become the new leader of the scientists or any sort of depressing ending

3. we save the friend
-she escapes with her friend (and maybe others) and they shut down this whole experiment fully? or expose it?
(maybe she goes on to live a normal life and pursue a career shes passionate about after realizing academics and success isn't worth your sanity LOL) 

then we gotta figure out the details of how she does either choice

**Comment by kodriq** [comment]
also im bringng this back again since it seems relevent

feel freee to edit this

level one

Visual:
Dark, enclosed (basement) hospital setting, likely underground, creepy

Mechanics:
flashlight to see in the dark
maybe like files/notes she can pickup and read (or maybe a zoom function?)

Goal(s):
figure out a clue of where she is(?)
expllore around, maybe some interactive objects (that give clues)

**Comment by ediehouston** [comment]
Yeah I like having two endings. For the one where she doesn't save her friend I think it would make sense if she became one of the scientists or something because 1. She would be smart from the test that successfully worked on her and 2. it could make sense why some of the scientists were there participating.

**Comment by ediehouston** [comment]
Like they could be former students or something that had been experimented on in the past. In this case the experiment could have been happening for a while.

**Comment by ediehouston** [comment]
Also is our character going to have multiple lives? Or like a health bar or anything. That could be cool

**Comment by kodriq** [comment]
yeah i like that a lot it would be cool
maybe she was the only one to fully pass the test so she is the smartest (technically) out of all the "passed" subjects there has ever been (so she climbed the ranks quickly)

**Comment by kodriq** [comment]
yeah definitely
i honestly think a sanity bar would be cool too but we would have to think on howd that work

**Comment by ediehouston** [comment]
> also im bringng this back again since it seems relevent
> 
> feel freee to edit this
> 
> level one
> 
> Visual: Dark, enclosed (basement) hospital setting, likely underground, creepy
> 
> Mechanics: flashlight to see in the dark maybe like files/notes she can pickup and read (or maybe a zoom function?)
> 
> Goal(s): figure out a clue of where she is(?) expllore around, maybe some interactive objects (that give clues)

For this I know people want to make the game set in a hospital. How should we incorporate that into our school idea.

**Comment by kodriq** [comment]
I feel ike plot wise its like a lab/hospital, but a hospital base for the map will work cause they did need medical equipment to bring them down there, and id also feel like they might have put a tracker or smth in there brain LOL So i feel like the basement would resemble a hospital.
Maybe the original test would look less like one, but our protagonist is waking up after things went wrong, so she's basically navigating the ruined labs which are functioning as puzzles for her.

**Comment by kodriq** [comment]
also i think we are making it so the lab/hospital is in the basement of the school

**Comment by ediehouston** [comment]
Yeah that's what I was thinking. So the school has a rundown basement where they are doing these tests.

**Comment by ediehouston** [comment]
I guess since the character just wakes up there we don't really see the exterior of the school, but we could have it on our start screen or something.

**Comment by kodriq** [comment]
yaa it was prob previously unused/used for storage before the scientists came and asked to use it
(or maybe it did have a use but has gone abandoned for years)

we could make it so "the school used to be a prison so they have an almost inescapable soundproof basement that was once used to contain criminals" but it probably doesn't  need that much lore

**Comment by kodriq** [comment]
well yeah, i mean maybe when the character escapes (in the save friend route?) they end up in the normal school area and they have to escape from scientists or teachers to get outside, but that would basically just be part of the ending i think

(since its in the basement, i always thought it would be cool if the school had the same layout as the basement, so maybe there's one final sequence where you must escape the school in the dark and try to remember the layout?)

**Comment by mya1919** [comment]
> > also im bringng this back again since it seems relevent
> > feel freee to edit this
> > level one
> > Visual: Dark, enclosed (basement) hospital setting, likely underground, creepy
> > Mechanics: flashlight to see in the dark maybe like files/notes she can pickup and read (or maybe a zoom function?)
> > Goal(s): figure out a clue of where she is(?) expllore around, maybe some interactive objects (that give clues)
> 
> For this I know people want to make the game set in a hospital. How should we incorporate that into our school idea.

**Comment by kodriq** [comment]
and yeah the other way the actual school could be used is in flashbacks, but that might be more cutscenes
(though we could make a playable flashback, which wold either be cool or confusing LOL)

**Comment by mya1919** [comment]
I think it would be kind cool if one of the endings she escapes from the school.
not sure if that was already said i was just reading through everything, might have missed it

**Comment by kodriq** [comment]
yeah we thought so too
u may have missed a bit haha so sorry about how much you have to read

**Comment by mya1919** [comment]
no all good i was trying to skim some of it so i might have missed that mb

**Comment by ediehouston** [comment]
What part of the story are we going to map out first?

**Comment by jeffaroundtheworld** [comment]
Sounds like story is mostly sorted.  Closing issues for cleanup
