### ISSUE TITLE
Create win/lose screens for end of game depending on if you rescued friend

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#84]

**Comment by kodriq** [comment]
im making a global variable, cause i figured we could make it so if you save the friend, it changes the variable, then depending on what the variable is when you walk through the exit, it changes what end screen you get 
example: variable is 0, saving the friend adds +1, then if the variable == 1 when you walk through the exit then it shows the "saved friend" scene, else it shows "didn't save friend" scene (neither are technically "lose", only dying will be a lose)

**Comment by jeffaroundtheworld** [comment]
Sounds great - what difference are you going to show on the ending screen to differentiate the two scenarios?

**Comment by kodriq** [comment]
well i think someone already made an end credits,so we could just add text that says "good ending" etc or something like that, or  could try draw something, or we could add a filter to make one end credit seem darker and more morbid for the sadder end
Id have to ask whoever made the current credit scene what they think

**Comment by kodriq** [comment]
^Maybe just add sadder music to one, and have them display different "win" text, and maybe even a piece of text that tells them how there choice resulted in the future
(like "Your decision to escape with your friend resulted in you choosing to live a happy life rather than a purely academic one, the two of you lived happily ever after :D")
